.PHONY: test test-onnx longmemeval-smoke longmemeval-recall-gate

test:
	go test ./...

test-onnx:
	go test -count=1 -run 'ONNX|IngestRetrieve|RecallGate' ./...

longmemeval-smoke:
	go test -count=1 -run IngestRetrieve ./cmd/longmemeval-server/...

longmemeval-recall-gate:
	go test -count=1 -run RecallGate ./cmd/longmemeval-server/...