#!/usr/bin/env bash
# Download hugot ORT + libtokenizers.a for the current OS/arch (dev/prod prefetch).
# Pins ONNXRUNTIME_VERSION to hugot v0.7.3 (1.25.1).
#
# Usage:
#   ./scripts/download_ort_deps.sh
#   DEST=/tmp/ort-deps ./scripts/download_ort_deps.sh
#   ./scripts/download_ort_deps.sh --cuda    # linux amd64 GPU ORT tarball only
#   eval "$(./scripts/ort_cgo_env.sh)"       # after download

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${DEST:-${ROOT}/testdata/ort-deps}"
ONNXRUNTIME_VERSION="${ONNXRUNTIME_VERSION:-1.25.1}"
GOMOD="${GOMOD:-${ROOT}/go.mod}"
CUDA=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cuda)
      CUDA=1
      shift
      ;;
    --dest=*)
      DEST="${1#*=}"
      shift
      ;;
    --dest)
      DEST="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '1,14p' "$0"
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

mkdir -p "${DEST}/lib"

tokenizer_version="$(grep 'github.com/daulet/tokenizers' "${GOMOD}" | awk '{print $2}')"
tokenizer_version="$(echo "${tokenizer_version}" | awk -F'-' '{print $NF}')"
tokenizer_version="${tokenizer_version//$'\r'/}"

if [[ -z "${tokenizer_version}" ]]; then
  echo "could not resolve github.com/daulet/tokenizers from ${GOMOD}" >&2
  exit 1
fi

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
case "${arch}" in
  x86_64|amd64) arch_norm=amd64 ;;
  arm64|aarch64) arch_norm=arm64 ;;
  *) echo "unsupported arch: ${arch}" >&2; exit 1 ;;
esac

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

case "${os}" in
  darwin)
    ort_archive="onnxruntime-osx-${arch_norm}-${ONNXRUNTIME_VERSION}.tgz"
    ort_url="https://github.com/microsoft/onnxruntime/releases/download/v${ONNXRUNTIME_VERSION}/${ort_archive}"
    tok_archive="libtokenizers.darwin-${arch_norm}.tar.gz"
    tok_url="https://github.com/daulet/tokenizers/releases/download/${tokenizer_version}/${tok_archive}"
    ;;
  linux)
    if [[ -n "${CUDA}" ]]; then
      ort_archive="onnxruntime-linux-x64-gpu-${ONNXRUNTIME_VERSION}.tgz"
    else
      ort_archive="onnxruntime-linux-x64-${ONNXRUNTIME_VERSION}.tgz"
    fi
    ort_url="https://github.com/microsoft/onnxruntime/releases/download/v${ONNXRUNTIME_VERSION}/${ort_archive}"
    tok_archive="libtokenizers.linux-amd64.tar.gz"
    tok_url="https://github.com/daulet/tokenizers/releases/download/${tokenizer_version}/${tok_archive}"
    ;;
  *)
    echo "unsupported OS: ${os}" >&2
    exit 1
    ;;
esac

echo "Downloading ONNX Runtime ${ONNXRUNTIME_VERSION} (${os}/${arch_norm}) -> ${DEST}/lib"
curl -fsSL -o "${work}/${ort_archive}" "${ort_url}"
tar -xzf "${work}/${ort_archive}" -C "${work}"
ort_dir="$(find "${work}" -maxdepth 1 -type d -name 'onnxruntime-*' | head -1)"
# Copy shared libs only (macOS tarballs ship libonnxruntime*.dylib.dSYM directories).
find "${ort_dir}/lib" -maxdepth 1 -type f \( \
  -name 'libonnxruntime*.dylib' -o -name 'libonnxruntime*.so*' \
\) -exec cp {} "${DEST}/lib/" \;

echo "Downloading tokenizers ${tokenizer_version} (${tok_archive}) -> ${DEST}/lib"
curl -fsSL -o "${work}/${tok_archive}" "${tok_url}"
tar -xzf "${work}/${tok_archive}" -C "${work}"
cp "${work}/libtokenizers.a" "${DEST}/lib/"

cat > "${DEST}/README.txt" <<EOF
hugot ORT deps for ${os}/${arch_norm} (ONNXRUNTIME_VERSION=${ONNXRUNTIME_VERSION})
Generated by scripts/download_ort_deps.sh — gitignored; safe to delete.
EOF

echo "ORT deps ready under ${DEST}/lib"
echo "Next: eval \"\$(./scripts/ort_cgo_env.sh)\""